### ISSUE TITLE
Small component allocator optimizations

### ISSUE THREAD

**Issue by guybedford** [WebAssembly/component-model#127]
The model of component communication being stack-based means that one can rely on a stack-based allocation strategy for cross-component calls in the current model, without needing a full dynamic realloc function.

The difficulty is of course that the embedded core Wasm memories will have their own memory allocation systems in place.

So I was thinking - couldn't the component model just bump the stack pointer of the application itself if we can reliably assume the mutable global export for this pointer. Stack sizes would need to be recalculated to handle the new component overhead, but there is already configuration to manage that, and bounding information flow seems fine as well to me. Alternatively the component model could even include its own ability to update these bounds for core wasm.

Perhaps there's an option to choose the allocation strategy here and use a stack strategy when desired for small shareable components that don't want excess overhead?

**Comment by lukewagner** [comment]
I think you're right that stack allocation is a useful optimization we want to allow.  One hard thing about baking stack allocation directly into canonical adapters is that there's a lot of variation we'd need to support for this optimization to be widely usable (e.g., supporting fibers/green-threads or different stack-growth/limit strategies).  Instead, I think one can achieve the desired stack allocation with the existing proposal by taking advantage of the fact that the `realloc` function used by `canon lower` is specified per-import/export and thus the toolchain can have N custom `realloc` functions for implementing various custom allocation strategies.  Because of [component non-reentrance invariants](https://github.com/WebAssembly/component-model/blob/main/design/mvp/Explainer.md#component-invariants), `global`s can be used to pass data to and from `realloc` without worrying about clobbering.  And because `realloc` is specified as an immediate, it's imminently inlineable by the AOT compiler.

IIRC, @alexcrichton might've even already implemented or explored doing something like this for implementing existing core wasm ABIs in terms of the Canonical ABI?

(If in the future we wanted to allow reentrance (via explicit opt-in on the signatures of the participating imports+exports, would be my preference), then we might want an extra `canonopt` for allowing the caller to pass in an `i32` that is propagated to all the calls to `realloc`, to provide `realloc` the necessary context without relying on `global`s.)

**Comment by guybedford** [comment]
Hmm, if reentrancy isn't allowed, then I think this ideally fits an arena allocation model much better than a stack allocation model? It's only if there is reentrancy on the same linear memory that one needs to handle progressive unwinding.

So realloc can just bump-allocate, and post-return clears the arena. And that can absolutely work with import call reallocs just fine. Note getting the reentrancy constraint was why I was originally thinking the "proper" way to do this would require some kind of stack tracking.

This seems like a really useful class of component model allocation for stateless components, and the level of granularity to explore it via custom realloc functions is certainly there. If I've got it correct, I really hope guest ecosystems properly explore this model, as it's really only stateful components and component resources that need malloc then.
