### ISSUE TITLE
WIT binary ABI contract

### ISSUE THREAD

**Issue by guybedford** [WebAssembly/component-model#128]
Currently the component model treats the WIT contract as the primary contract and spec for component communication.

When using WIT, the underlying core Wasm does in fact embed binary encoding assumptions of the WIT in its coding. That is - the public API surface area of the components model, in its current form, does actually include the WIT binary ABI representation that components use to communicate, and changes to this ABI represent major changes to the component model itself (eg a component with one ABI cannot support a host or component written to an alternative ABI).

I like that the door is still open on these decisions, and that things like adapter functions haven't necessarily been ruled out entirely, but it seems important to be explicit about the WIT binary assumptions in this specification at least for now, perhaps even explicitly in treating it as a part of the overall specification space.

**Comment by lukewagner** [comment]
I might be missing your point, so please feel free to let me know that, but, iiuc, I think component binaries do already have the necessary separation of "high-level type" and "low-level ABI" that I think you're advocating for.  In particular, because components explicitly define their own adapters as an encapsulated implementation detail and because these adapters are defined to produce/consume an ABI-independent set of high-level abstract values, we are preserving full optionality in the future to add new low-level ABI options for the same types (including the fully-programmable model that we originally were working on in Interface Types).

So for example, when I write:
```
(component
  (core module $Core ...)
  (core instance $core (instantiate $Core ...))
  (func (export "foo") (param "s" string) (result string)
    (canon lift
      string-encoding=utf8
      (memory (core memory $core "mem")
      (realloc (core func $core "foo"))
    )
  )
)
```
the `canonopt`s of the `canon lift` definition are implementation details of the component not visible to the outside world.  The only thing the outside world can see is the type:
```
(component
   (func (export "foo") (param "s" string) (result string))
)
```
Thus, if a client lowers this function with a different string encoding, that's fine because the component-model has enough semantic knowledge of what `string` means to do the transcoding (and indeed, this is required by the c-m for the current 3 `string-encoding` options).

**Comment by guybedford** [comment]
Thanks for clarifying. Yes, for the person consuming the component, the ABI is indeed fully abstracted. Components can interoperate without needing to know the details of eachothers binary ABIs which is great. This brings a lot of flexibility, in theory even potentially allowing component ACIs (application canonical interface!?) to have non-breaking upgrade paths (adding a new field to a record, adding a new enum, adding new optional params to functions), which is an important property to have in a registry ecosystem.

Even wasm-compose workflows remain encapsulated due to the incorporated bundling structure of nesting components, which is great.

For the person authoring the component, the WIT toolchain binary details matter. At this level at least - their specific choice of WIT toolchain will affect their binary assumptions, and I agree that is toolchain-specific versioning work out of scope of this specification.

And also for the host, the exact binary contract is also a part of the implementation, at least until exact internal adapter functions. That is, I believe the binary ABI of the canonical functions is part of the host embedding spec at least. That could certainly be treated as a separate spec to the component model itself though.

Finally, if an optimization tool wants to remove component boundaries and mash code and linear memories together and do unused function removals, that would be a more advanced optimization based on exact binary ABI matching as well. And depending on how the binary ABI is designed, possibly or possibly not supporting smoothing over ecosystem ABI version differences.

**Comment by lukewagner** [comment]
Yes, that all sounds right.  So going through the cases:

For the person authoring the component, my expectation is that:
1. `wit-bindgen` and other bindings generators would use the default `canonopt`s but provide flags that allow setting non-default `canonopt`s (either for the whole component or even on a per-import/export basis). This information gets put into a custom section (along with the Wit type information, encoded as a component-model type section) so that it can be picked up by `wit-component` which emits the actual `canon` definitions that embed these `canonopt`s in the final component.  As a concrete example, JS-to-wasm will want to change the default `string-encoding` from `utf8` to `latin1+utf16`.
2. The top-level language toolchain CLI/SDK will set these `wit-bindgen` options as appropriate for that language's end-to-end toolchain so the developer doesn't have to worry about it (the developer doesn't want to invoke `wit-bindgen` anyway).

For the host running components, the host has to handle *all* valid configurations of `canonopt`s.  However, host glue-code generation (e.g., from `wit-bindgen --host`) can make this easier by handling the cases in the generated glue code.  It does mean that, when a new `canonopt` is added, hosts need to be upgraded to run components using the new `canonopt`, but that's business as usual with any new wasm feature (like a new instruction).

Lastly, optimizers are roughly in the same boat as hosts: they have to handle all possible `canonopt`s and combinations thereof (when optimizing cross-component calls).  It's best of course if both sides of a call have the same `canonopt`, so it's useful for there to be clear "default" `canonopt`s so that, all else being equal, components will tend to have these unless there's a good reason not to.

**Comment by guybedford** [comment]
I guess my original question is then just where the binary `canonopt` mapping details get specified, and if this belongs to the host or this spec, or will be subsumed by adapters.

> It's best of course if both sides of a call have the same canonopt

One concern here is as I mentioned the concept of component interface non-breaking changes. It is a property of the binary encoding itself whether or not this will be possible in optimized calls. Perhaps non-exact binary calls just aren't possible to have lift/lower removal optimizations. But it's worth calling out this use case as well.

**Comment by lukewagner** [comment]
> I guess my original question is then just where the binary canonopt mapping details get specified

Ahhh, this may be the root of the question that I missed initially.  `canonopt` definitely belongs in the component-model spec and is currently informally defined [here](https://github.com/WebAssembly/component-model/blob/main/design/mvp/Explainer.md#canonical-definitions), [here](https://github.com/WebAssembly/component-model/blob/main/design/mvp/Binary.md#canonical-definitions) and [here](https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md#canonical-definitions).  Thus, `canonopt` is just a normal part of the specified semantics like any part of the component model.

**Comment by guybedford** [comment]
I apparently can't read it turns out! Yes this is what I was after, will review further thank you.
