### ISSUE TITLE
Spec-defined name section for components

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/component-model#14]
Similar to how core wasm has a well-defined `name` custom section I think it would also be good to define one for the component model with all of the types of items in the component model itself. Additionally similar to how core wasm has an [extended name section proposal](https://github.com/WebAssembly/extended-name-section) to extend the name setion to all nameable items in core wasm I think it would be nice to name all items in the component model as well (not just a subset).

One of the trickier things perhaps about this would be how to name types-in-types. For example a module type introduces a new index space for types. Core wasm doesn't provide clear precedent here to map from although the component model can perhaps create its own covnention for defining the names here.

**Comment by lukewagner** [comment]
I think you're right, we should add a custom name section.  If you want and are motivated before I get to it, feel free to make a PR.

That being said, even without a name section present, it seems like an automatic name-derivation scheme could do pretty well (much better than in core wasm) due to the import/export names everywhere, and so it might make sense to build that in early:
* An imported/exported definition would of course use the import/export name.  An exported function definition could additionally include the name of the core export it was `canon.lift`ing.
* Types could be structurally rendered in `wit` or `wat` (which is mostly what you'd want to see), annotated with their export name (if they had one), which would be a lot more meaningful than `i32` (and not require the name manging/unmangling stuff core wasm does to recover the source-level signatures)
* Instances of imported modules/components could inherit the import name (suffixed with, say, " instance")

The main remaining case the above won't cover is when you have multiple nested modules or components and instances of these.  Even in the short term, I think we'll have this with the glue/shim modules we were talking about earlier, so I can see the value in naming these so one can distinguish the "main" module from the "shim" modules.
