### ISSUE TITLE
Cannot faithfully represent type aliases in exported instances from WIT

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/component-model#151]
Given a WIT document of the form:

```
interface foo {
  type a = u8
  type b = a
  c: func(a: a) -> b
}

default world the-world {
  export foo: self.foo
}
```

when this is actually transformed into a component that implements `the-world` the current translation of `wasm-tools` looks like:

```wasm
(component
  (core module (;0;) (;... core wasm module here ...;) )
  (core instance (;0;) (instantiate 0))
  (type (;0;) u8)
  (type (;1;) (func (param "a" 0) (result 0)))
  (alias core export 0 "foo#c" (core func (;0;)))
  (func (;0;) (type 1) (canon lift (core func 0)))
  (instance (;0;)
    (export "a" (type 0))
    (export "b" (type 0))
    (export "c" (func 0))
  )
  (export (;1;) "foo" (instance 0))
)
```

The problem with this format, however, is that the type alias cannot faithfully be represented in this format. In the exported instance it has

```
    (export "a" (type 0))
    (export "b" (type 0))
```

which loses the information that "b" is a reexport of "a". This is due to the fact that the export introduced in "create an instance from this bag of exports" doesn't get its own index for "b" to refer to.

This will furthermore be a problem with validation of resources/records/etc where it's not possible to execute the `canon lift` with a parameter that has a type which requires a name. The type shouldn't be exported from the root of the component, only a sub-instance, so there's no way to introduce the type index before the `canon lift` happens.

I believe @lukewagner has an idea of how to fix this but I wanted to open an issue since I'm about to write a FIXME in code that needs to reference this problem.

**Comment by lukewagner** [comment]
Thanks for the nice writeup!  So I think the solution here has two parts:
1. have validation of these inline-instances create a fresh set of nested index spaces (just like component/instance types) so that type indices can be introduced and used by exports, just like in component definitions and component/instance types.
2. allow (but not require) types to be placed on exports (using an `externdesc`, just like imports) which, when present, would ascribe the type of the export, making the grammar: `export ::= (export <externname> bind-id(<externdesc>)? <sortidx>)`

With these two additions, I think your example could be written:
```wasm
(component
  (core module (;0;) (;... core wasm module here ...;) )
  (core instance (;0;) (instantiate 0))
  (alias core export 0 "foo#c" (core func (;0;)))
  (type (;0;) (func (param "a" u8) (result u8)))
  (func (;0;) (type 0) (canon lift (core func 0)))
  (instance (;0;)
    (type (;0;) u8)
    (export "a" (;1;) (type 0))
    (export "b" (;2;) (type 1))
    (type (;3;) (func (param "a" 1) (result 2)))
    (alias outer 1 0 (func (;0;)))
    (export "c" (func (type 3)) (func 0))
  )
  (export (;1;) "foo" (instance 0))
)
```
Validation would check that the exported `(func (;0;))`'s type is a subtype of `(type 3)`, which it is, before judging that the type of this export in the containing instance type is `(type 3)` which now captures the exported type names and supports resource types.  Note that I'm using the optionality of types in exports in `a` and `b` but, if I wanted to, I could more-verbosely have written, e.g., `(export "a" (type (;1;) (eq 0)) (type 0))`.

Does that make sense?  If so, I'll write this up in a PR soon.

**Comment by alexcrichton** [comment]
That sounds reasonable to me, but could the subtype check be replaced with an equality check? I think right now subtyping only shows up during instantiation when a check is performed on what was provided and was was required, and I personally think that's a nice property to have where subtyping is only applicable in one location.

**Comment by lukewagner** [comment]
Equality seems sufficient for solving the actual problem at hand, so yeah, we could conservatively start with that and see if a need arises for more general subtyping.
