### ISSUE TITLE
Introduce types with generic parameters

### ISSUE THREAD

**Issue by r-muhairi** [WebAssembly/component-model#153]
Hi,

I can't seem to understand why does the component-model specify only a handful hard-coded HKTs as opposed to providing some support for ypes with generic parameters?

No, their equivalents aren't valid, for example the equivalent of option was said to be
```wit
variant option {
    none,
    some(ty),
}
```
However, as this may be a technically correct HKT, its nothing but incorrect.

As such, I'm proposing the following a modified definition for records and variants.
```
variant-items ::= 'variant' id ty-param ...
record-items ::= 'record' id ty-param ...
```
where
```
ty-param ::= '<' id ( ',' id)* '>'
```
so that we can specify types with generic parameters like the following
```wit
variant option<t> { 
   none, 
   some(t)
}
```
And introducing a new type to encapsulate  types with generic parameters
```
ty ::= ... | id ty-param
```

I would love to know why did the design move onto that direction initially, and if there's any reason why we can't introduce types with generic parameters if not possible.

Thank you

**Comment by lukewagner** [comment]
Generics are a very complicated and nuanced feature and, if not done carefully, could fundamentally change the entire compilation model, cost model, host implementation complexity (see, e.g., generics in the CLR vs. JVM vs. AOT-compilation models like C++/Rust) and bindings generation complexity for each language.  For now, in the component model MVP, we're trying to keep things as narrowly scoped as possible and only add what's necessary for the use cases we're seeing in WASI and emerging wasm embeddings and, fortunately, these don't seem to need full-blown value-type generics of the sort you're describing.

**Comment by ribosomerocker** [comment]
Hey, I just discovered this project and I think it's really cool! I have huge respect for the authors, thank you for creating this.

First off, to reply to the OP: You are correct. The types that
```
variant option {
    none,
    some(ty),
}
```
represents would be closer to an *extistential* optional type. For those unaware, existentials are the feature that's known to be able to implement dynamic types and dynamic dispatch in more expressive type systems. A true `option` static type would actually tell you which type it's supposed to be an optional of, otherwise, this type would have some unexpected, surprising behavior compared to other languages.

Secondly, to reply to the comment:
I personally agree that generics are a complicated and nuanced feature, which makes it important to get them right. As you can see with optionals and results, they're a very important feature for programming entirely, and we wouldn't want to go the Golang route. Considering that this project is pretty much "types for wasm,", I'd also say generics would be expected by people in an MVP. Plus, past a certain point, it's harder to implement new features that are as big as generics (that's why Golang took so long), so it might be better if work on implementing them starts earlier rather than later -- But that's just my input, I don't mean to rush you or anything! if you consider generics to be too complex to include into an MVP, that's fine. But I would love to see them in this project any time soon!

**Comment by jeffparsons** [comment]
@ribosomerocker I wouldn't worry about a Golang-type scenario emerging here. Even though generics are not being considered for MVP, I've seen many discussions (in meeting minutes, Zulip threads, etc.) about how current feature designs would interact with generics in future. So I believe the people working on this are very much thinking about a future that might well contain generics, and treating it as important to leave the door open to a high quality implementation. Cf. Golang where the authors were originally explicitly against ever adding generics because they saw them as antithetical to the language's design goals, not merely too complex to implement early on.

**Comment by r-muhairi** [comment]
As this seems like a feature too large to undertake for an MVP, I'll close this Issue for now and it can be reopened/recreated on a later date.

**Comment by ribosomerocker** [comment]
Yes, though I'd like to emphasize the first part about the Optionals not being quite optionals; I believe simply a different implementation that parameterises them on the underlying type will be enough without needing to implement general generics.
