### ISSUE TITLE
Canonical ABI for load_string_from_range looks wrong?

### ISSUE THREAD

**Issue by GordonSmith** [WebAssembly/component-model#217]
Assuming `tagged_code_units` is meant to be the string length, then the `byte_length` calculation for `utf8` looks wrong here:  https://github.com/WebAssembly/component-model/blob/main/design/mvp/canonical-abi/definitions.py#L448C1-L474C57

**Comment by lukewagner** [comment]
I might be missing your point, but `tagged_code_units` is meant to be the number of code units relative to the selected encoding.  Since the [code unit](https://unicode.org/glossary/#code_unit) (not to be confused with [code point](https://unicode.org/glossary/#code_point) for UTF-8 is a byte, then `tagged_code_units` for UTF-8 is indeed the byte length of the string in memory.

**Comment by GordonSmith** [comment]
@lukewagner thanks for clarifying that!
