### ISSUE TITLE
Mapping from JS values to flags is unclear

### ISSUE THREAD

**Issue by Liamolucko** [WebAssembly/component-model#26]
The conversion from JS values to flags is defined to be the same a Web IDL dictionary of boolean fields; however, it doesn't specify whether the booleans are required or optional.

If they're required, an error should be thrown if a field is missing or undefined; using an example of `flags { a, b, c }`, `ToWebAssemblyValue({ a: true, b: undefined })` would throw an error. I'm not entirely sure what the booleans being optional would entail; Web IDL defines them as just not being present in the dictionary, which obviously isn't possible for interface types.

Also, just to double-check - the Web IDL conversion converts values to booleans by checking truthiness, so `ToWebAssemblyValue({ a: 3, b: "", c: {} }) == ToWebAssemblyValue({ a: true, b: false, c: true })`. Is this the intended behaviour?

**Comment by lukewagner** [comment]
My initial impression is that it would be reasonable to have the implied boolean fields of `flags` be optional, as this matches the usual way bit-flags are used in practice.  It's also the default for dictionary fields (unless `required` is specified), but probably it'd be good to update the explainer to explicitly call this out.

For the latter question, yes, the idea is to try to inherit the (extremely nuanced and particular) JS coercive behavior of Web IDL rather than trying to invent our own scheme.
