### ISSUE TITLE
Rename `float32`/`float64` back to `f32`/`f64`

### ISSUE THREAD

**Issue by esoterra** [WebAssembly/component-model#277]
As of preview2, the NaN-canonicalization rules have been relaxed and so in preview 2 the set of semantic values of `float32` is the same the set for core wasm `f32` (and likewise for `float64`/`f64`). 

Since this was the main motivator for distinguishing between core wasm `fXX` and component model `floatXX` types, we should consider gradually renaming the component model floating point types to match core wasm again.

**Comment by sunfishcode** [comment]
I find it useful to think of the rules not as "the bits might be randomized" but instead as "component-model floating-point types only have a single NaN value", with the randomization just being an artifact of how they're encoded in core wasm.

**Comment by sunfishcode** [comment]
Independently of what the types are named, is it desirable to allow multiple distinct NaN payloads to be observed when passing values out to non-wasm? It would seem that any code depending on that functionality would be unvirtualizable.

**Comment by lukewagner** [comment]
The original motivation for the change was to avoid forcing an extra canonicalization pass when, e.g., passing a `list<f32>` out to a host library.  The allowed randomization means you can't (or at least *shouldn't*) depend on seeing any particular NaN payload, although you also can't depend on seeing exactly one or a particular one either.

**Comment by sunfishcode** [comment]
With #279, the component-level `float32` and `float64` values are different from core-wasm `f32` and `f64, in that they only have a single NaN value. Implementations can omit canonicalization and randomization instructions when doing lifting and lowering together, but this is a permitted optimization rather than a property of the types.

I've also now posted https://github.com/WebAssembly/component-model/pull/288 to add more documentation.

**Comment by lukewagner** [comment]
Yep, with those semantic changes, I think you're right.  Once we merge #288, I think we can close this issue, but I'll wait a while to collect more thoughts if anyone disagrees.

**Comment by rossberg** [comment]
Hm, I understand the motivation, but as is I find the naming discrepancy more confusing than helpful, because there is nothing in the name which actually conveys _how_ `floatN` is different, and moreover, why the naming scheme deviates from that for ints. As is, it just looks like a seemingly random choice and all it does is create a mental impedance mismatch.

Feel free to ignore, but short of a more self-explanatory alternative, I think I'd prefer the short names, since the semantics still is close enough and the difference, where it matters at all, implied by context.

**Comment by lukewagner** [comment]
I definitely like the aesthetics of `f32`/`f64` and their symmetry with the integral names, but I had thought that different sets of semantic values forced different names.  But now that I say that, that reminds me that we do of course have component-level `func` and `instance` types that are wholly distinct from the core-level `func` and `instance` types and we distinguish them via `core:` prefix when necessary, so I suppose we could do that for `f32`/`f64` as well.

**Comment by sunfishcode** [comment]
Using `f32`/`f64`, and just documenting the differences, sounds good to me too.

**Comment by esoterra** [comment]
I fully agree with @rossberg's explanation of the real main issue and @lukewagner's framing about the `core:` prefix and component/module value types already being separate.

If we're all on the same page now, I think the main question is when/how to do this. I imagine we'll want to roll it out gradually so that for a while both are acceptable but only `f32`/`f64` are emitted to give people time to make the switch. Should we also wait in general until after the preview 2 release or would it be better to tackle this sooner than later?

**Comment by sunfishcode** [comment]
Regardless of when we do the full switch, we should start updating tools to at least recognize `f32`/`f64` sooner rather than later. I submitted  https://github.com/bytecodealliance/wasm-tools/pull/1356  to add `f32` and `f64` recognition in wit-parser.

**Comment by lukewagner** [comment]
Great, thanks for doing that.  Even though this isn't a breaking binary format / runtime change, to avoid confusing/breaking folks, I suppose we should wait for that change to merge, percolate a few months, and then we can switch over the WASI proposals and Explainer.md/WIT.md in this repo.

**Comment by esoterra** [comment]
Is there anything left to do for this change?

**Comment by lukewagner** [comment]
I don't think so; thanks everyone!
