### ISSUE TITLE
Inconsistency in Grammar

### ISSUE THREAD

**Issue by thesuhas** [WebAssembly/component-model#333]
Hi,
In the grammar there is the following line: The next two productions, `core:instance` and `core:alias`, are not currently included in Core WebAssembly, but would be if Core WebAssembly adopted the [module-linking](https://github.com/WebAssembly/module-linking/blob/main/proposals/module-linking/Explainer.md) proposal.

But, if you look at the productions of the component, there is no `core:alias`. I was just wondering if this could be cleared up.

https://github.com/WebAssembly/component-model/blob/main/design/mvp/Explainer.md#grammar

**Comment by lukewagner** [comment]
Thanks, good find!  I think it must have been removed a while back and the text wasn't updated accordingly.  Fixed in [this](https://github.com/WebAssembly/component-model/commit/145752a9795f326875c347527040d0e2ebe87c35) commit.  I'll close this issue, but feel free to reopen if there's anything else to say.
