### ISSUE TITLE
How does resource drop function get realized by use-site component?

### ISSUE THREAD

**Issue by dannypsnl** [WebAssembly/component-model#409]
By dump binary, I found
```
[instance 8] ComponentImport { name: ComponentImportName("wasi:filesystem/types@0.2.0"), ty: Instance(15) }

import [func 1] Import { module: "wasi:filesystem/types@0.2.0", name: "[resource-drop]descriptor", ty: Func(0) }

alias [type 18] InstanceExport { kind: Type, instance_index: 8, name: "descriptor" }

[core func 7] ResourceDrop { resource: 18 }
```
1. instance 8 is a component `wasi:filesystem/types@0.2.0`
2. The resource-drop function is imported as func 1
3. The type 18 is get from instance 8, name `descriptor`
4. A resource drop of type 18 is created (loweing)

But where is the place of func 1? 

----

source: https://github.com/second-state/component-model-tests/tree/main/add
package: wit-bindgen-rt = { version = "0.34.0", features = ["bitflags"] }

**Comment by dannypsnl** [comment]
Let me refine the question a bit: I wrote a implementation of `wasi:filesystem/types@0.2.0`, in this case, where should I place the `[resource-drop]descriptor`?

My original idea was
- `[resource-drop]descriptor` belongs to `wasi:filesystem/types@0.2.0` directly
- The use-site component will import `[resource-drop]descriptor` as `func x`
- Later but before `resource.drop rt` shows up, something should set `x` to `rt` (The handle stores this optionally)

From what you say, I thought
- `[resource-drop]descriptor` belongs to the component instance of `descriptor`
- The index of `resource-drop` is pre-defined in the component instance of `descriptor`
- The import up there has different meaning

**Comment by dannypsnl** [comment]
Since I'm working on WasmEdge to make it a component runtime, I believe how wasmtime deal with it will be helpful.

**Comment by alexcrichton** [comment]
I think solving this might require a bit of a shift in how you're thinking about this perhaps? There isn't a 1:1 equivalence of imports in core wasm to imports in components. For example a component import could be `canon lower`'d multiple times with different options which means the same component import might be used by multiple core modules. Similarly the core import of `[resource-drop]descriptor` doesn't actually correspond to any component import at all, it's synthesized internally in the component with a `canon resource.drop` intrinsic. 

For example:

> I wrote a implementation of wasi:filesystem/types@0.2.0, in this case, where should I place the [resource-drop]descriptor?

The answer to this in Wasmtime is "nowhere, it's in the runtime". WASI proposals in Wasmtime don't implement resource management since that's covered by the component runtime. The component itself decides to create a `resource.drop` in a particular context which is not possible to satisfy at the WASI implementation layer itself.

Furthermore `resource.drop` in different components can mean different things so there's no one canonical definition of a drop function. Each component will operate on a different table of resources which means that each time a `resource.drop` function is declared it's effectively binding to a different table as well  to operate on.

**Comment by dannypsnl** [comment]
I see, do you mean there is no need to have any origin function for `canon resource.drop`, itself will generate a new function instance? If so, then you can close the issue as solved.
