### ISSUE TITLE
Zero-sized flags

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/component-model#75]
I've recently run into an issue in a fuzz-generated case with a question about what to do with zero-sized flags. This is for types of the form:

```
(type (flags))
```

Currently I believe that this is allowed via the grammar for flags and the component model, but the canonical ABI is somewhat inconsistent. For example `num_i32_flags` would return 0 for this but `size_flags` would return 1. I figured it might be worth taking this opportunity to ask whether this should be supported or not:

* If so, I think `size_flags` may want to be updated to be 0 for zero flags
* Otherwise I think the grammar would be tweaked to require 1+ flag names and that should be all that's necessary

**Comment by lukewagner** [comment]
Oops, good catch!  I agree `size_flags` should return 0 for zero flags (analogous to `size_record`).  It's a good question of whether we should require 1+ flag names, though.  My impression is that, unless it causes additional burden, since `record` and `tuple` allow 0 fields, so should flags.  I wondered whether it would be unnatural for binding generation, but it seems like, in any case, bindings will always need to define a "no flags set" value, and this will be the *only* valid value for a 0 flags.

**Comment by alexcrichton** [comment]
Personally I would agree that 0-sized tuples and 0-sized records means 0-sized flags would be good to allow (and I'm not aware of any cost associated with it myself)
