### ISSUE TITLE
The canonical ABI's type syntax isn't quite compatible with WIT

### ISSUE THREAD

**Issue by Liamolucko** [WebAssembly/component-model#86]
There are a couple cases where the canonical ABI's mangling of function signatures isn't valid according to WIT.md, specifically around  optional types (note: I've left off the identifiers in WIT like they are in the canonical ABI):

<table>
<tr>
<th>WIT</th>
<th>Canonical ABI</th>
</tr>
<tr>
<td>

```wit
variant {
    foo,
    bar(string),
}
```

</td>
<td>

```wit
variant {
    foo(_),
    bar(string),
}
```

</td>
</tr>
<tr>
<td>

`result`

</td>
<td>

`result<_, _>`

</td>
</tr>
<tr>
<td>

`result<T>`

</td>
<td>

`result<T, _>`

</td>
</tr>
</table>

I think that either WIT should be made more permissive to accept these cases as well, or the canonical ABI should be changed to match WIT. (Or some combination of the two on a case-by-case basis.)

**Comment by lukewagner** [comment]
Good catch!  I oscillated on this design a bit and must've gotten out of sync because my goal was indeed for the canonical ABI to produce valid wit.  So #71 took out `unit`/`_` as general types and introduced `_` only as a syntactic placeholder in `result` (for lack of a better idea for how to syntactically express "no success value, only a fail value"), so I think it makes sense to move the Canonical ABI to wit in all 3 cases.
