### ISSUE TITLE
Concurrent access to streams

### ISSUE THREAD

**Issue by badeend** [WebAssembly/component-model#97]
I'm incorporating `streams` into the wasi-sockets proposal (https://github.com/WebAssembly/wasi-sockets/pull/10).

I think I've got the hang of when it concerns simple, sequential streams (as in `stream<u8, ...>`). But, I don't know how streams will behave when they represent discrete, fully independent values.

For example in my PR, `tcp-socket::accept()` returns a stream of client sockets. Each accepted client socket is fully independent from each other. Preferably, multiple threads should be able to pop values off the `accept` stream in parallel. Same goes for reading packets off an UDP socket.

I'm aware the component model doesn't support multi-threading yet, but I was curious whether you already had any thoughts on this yet.

Depending on the use-case, I can see reasons for both allowing and disallowing concurrent access, so maybe a separate type `shared-stream<>` could be used to enable the additional capability.

Note: I'm not talking about tee-ing; every value should be read off the stream exactly once.

**Comment by lukewagner** [comment]
Thanks so much for looking into using streams for sockets and that's a great question.  So one useful consequence of the async nature of streams is that, since the producer and consumer are not synchronously calling into each other when they read/write, whether the consumer is doing multi-threaded operations is not observable to the producer, and vice versa.  Thus, I don't think we need a separate `shared-stream`; I believe multi-threading can be a per-component impl detail supported by adding additional variants (expressed as new `canonopt`s) of the stream built-ins.

It seems like there are a few complementary ways to go about this.  A more-traditional route would be to just allow the existing built-ins to be called from multiple threads (making the imported core functions `shared`, as defined in [this proposal](https://dl.acm.org/doi/10.1145/3360559)) so, e.g, you could have N threads all `canon wait`ing and then when events arrive the runtime wakes up whichever thread is ready and next.  Another option is to take advantage of the lightweight stacks coming with core stack-switching and adopt a more [GCD](https://en.wikipedia.org/wiki/Grand_Central_Dispatch)-like approach in which the spawning of threads is controlled by the runtime (avoiding the usual problem with, e.g., [navigator.hardwareConcurrency](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/hardwareConcurrency), where you get M independent components each thinking they own the machine and creating N threads, and providing the host runtime more control over resource allocation).

One thing I'll note about why we haven't dug as much into this direction yet: looking at how wasm is being used in practice in non-browser contexts today, the "big `accept()` loop" usually happens in the host runtime, which spawns many independent isolated low-concurrency wasm instances.  That of course won't be the case forever, so we do need to plan for the future, but I think it does buy us time to develop a strong single-threaded (but massively parallel at the host level) concurrency story that handles the hopefully-very-common case (i.e., even after there was multi-threading support, most components should still be single-threaded, achieving parallelism "a level up", either in the host or a parent component).

**Comment by lukewagner** [comment]
> May I summarize your first paragraph as: I don't have to worry about concurrent access. Streams have that capability baked in.
?

If you tweak "have that capability" to "would one day gain that capability" (= multi-threading support), then yes :)

> A wasm instance per request is indeed a nicer programming model. However, with the wasi-sockets proposal I'm specifically after POSIX-compatibility, which includes direct access to the "big accept() loop" :)

That makes sense, and I totally agree that supporting this code in the short-term is an important goal.  The only nuance I was trying to convey was why, at least initially (in the "MVP"), it doesn't seem like we'll be needing to be support many thousands of concurrent connections handled by a single component instance (requiring multi-threading support).

**Comment by badeend** [comment]
Thanks!
